# Generated by Django 4.2.23 on 2025-08-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Admission', 'Admission'), ('Annual', 'Annual'), ('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=20)),
            ],
        ),
    ]
